AWSTemplateFormatVersion: '2010-09-09'
Description: Camada de Computação

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso SSH, HTTP e Grafana
      VpcId: !ImportValue VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  PublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      KeyName: !Ref KeyName
      SubnetId: !ImportValue PublicSubnetId
      SecurityGroupIds:
        - !Ref SecurityGroup
      ImageId: ami-0fc5d935ebf8bc3bc
      Tags:
        - Key: Name
          Value: arq-infra-ec2-public
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y docker

          systemctl start docker
          systemctl enable docker

          usermod -aG docker ec2-user

          docker run -d -p 3000:3000 grafana/grafana

  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      KeyName: !Ref KeyName
      SubnetId: !ImportValue PrivateSubnetId
      SecurityGroupIds:
        - !Ref SecurityGroup
      ImageId: ami-0fc5d935ebf8bc3bc
      Tags:
        - Key: Name
          Value: arq-infra-ec2-private

Outputs:
  PublicInstanceId:
    Value: !Ref PublicInstance

  PrivateInstanceId:
    Value: !Ref PrivateInstance