AWSTemplateFormatVersion: '2010-09-09'
Description: Camada de Monitoramento - CloudWatch Dashboard para EC2 Pública

Resources:
  PublicEC2Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "Public-EC2-Monitoring-${AWS::Region}"
      DashboardBody:
        Fn::Sub:
          - |
            {
              "widgets": [
                {
                  "type": "metric",
                  "x": 0,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "metrics": [
                      [ "AWS/EC2", "CPUUtilization", "InstanceId", "${InstanceId}" ]
                    ],
                    "view": "timeSeries",
                    "stacked": false,
                    "region": "${AWS::Region}",
                    "title": "Percentual de Uso da CPU",
                    "period": 60
                  }
                },
                {
                  "type": "metric",
                  "x": 12,
                  "y": 0,
                  "width": 12,
                  "height": 6,
                  "properties": {
                    "metrics": [
                      [ "AWS/EC2", "NetworkIn", "InstanceId", "${InstanceId}" ],
                      [ ".", "NetworkOut", ".", "." ]
                    ],
                    "view": "timeSeries",
                    "stacked": false,
                    "region": "${AWS::Region}",
                    "title": "Tráfego de Rede (In/Out)",
                    "period": 60
                  }
                },
                {
                  "type": "metric",
                  "x": 0,
                  "y": 6,
                  "width": 8,
                  "height": 6,
                  "properties": {
                    "metrics": [
                      [ "AWS/EC2", "EBSByteBalance%", "InstanceId", "${InstanceId}" ]
                    ],
                    "view": "singleValue",
                    "region": "${AWS::Region}",
                    "title": "EBS Byte Balance %",
                    "period": 300
                  }
                },
                {
                  "type": "log",
                  "x": 8,
                  "y": 6,
                  "width": 16,
                  "height": 6,
                  "properties": {
                    "query": "SOURCE logGroups(namePrefix: [\"/ec2/syslog\"], class: \"STANDARD\") START=-604800s END=0s | fields @timestamp, @log, @message | sort @timestamp desc | limit 10000",
                    "region": "${AWS::Region}",
                    "stacked": false,
                    "title": "Logs Analytics - Syslog",
                    "view": "table"
                  }
                }
              ]
            }
          - InstanceId: !ImportValue PublicInstanceId

  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "CPU-High-Alarm-${AWS::Region}"
      AlarmDescription: "Alerta quando o uso de CPU atingir 5%"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: InstanceId
          Value: !ImportValue PublicInstanceId
      AlarmActions:
        - !ImportValue arq-infra-alert-topic-arn
