AWSTemplateFormatVersion: '2010-09-09'
Description: Camada de Mensageria

Resources:

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: arq-infra-alerts

  AlertTopicEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: email
      Endpoint: primeleadautomation@outlook.com  # Email do projeto

Outputs:
  TopicArn:
    Description: ARN do tópico de alertas/ETL (Lambdas fazem sns:Publish)
    Value: !Ref AlertTopic
    Export:
      Name: arq-infra-alert-topic-arn